# Use root/example as user/password credentials
version: '3.6'

services:
  permacall_mysql:
    container_name: permacall_mysql
    ports: 
        - "3306:3306"
    image: mysql:5.6.43
    command: --default-authentication-plugin=mysql_native_password
    tmpfs:
    - /var/lib/mysql
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - MYSQL_DATABASE=Permacall
    - MYSQL_USER=Permacall
    - MYSQL_PASSWORD=8kejnziH!P4IB0Z2ChYz@mo&F#!54hxN