// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Permacall.Persistence;

namespace Permacall.Persistence.Migrations
{
    [DbContext(typeof(PermacallDbContext))]
    [Migration("20190310221555_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Permacall.Domain.Entities.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("LastStrike");

                    b.Property<int>("NormalCount");

                    b.Property<int>("OperatorCount");

                    b.Property<string>("Password");

                    b.Property<int>("PermissionGroup");

                    b.Property<int>("Strikes");

                    b.Property<string>("Username");

                    b.Property<bool>("toEdit");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
